### ISSUE TITLE
NoSuchMethodError: emu.grasscutter.server.dispatch.DispatchServer.getServer()

### ISSUE THREAD

**Issue by mikuyourworld** [4Benj/gcgm-plugin#1]
I am using lastest dev erison of grasscutter.
And loaded the gcgm plugin, but it throw this error.

`Exception in thread "main" java.lang.NoSuchMethodError: 'com.sun.net.httpserver.HttpServer emu.grasscutter.server.dispatch.DispatchServer.getServer()'`
        `at com.benj4.gcgm.GCGMPlugin.onEnable(GCGMPlugin.java:88)`
        `at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:116)`
        `at java.base/java.util.HashMap.forEach(HashMap.java:1421)`
        `at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:114)`
        `at emu.grasscutter.Grasscutter.main(Grasscutter.java:100)`

**Comment by 4Benj** [comment]
Hi!
Thanks for downloading the plugin (even though it isn't really usable atm).
Due to the fact that grasscutter and this plugin is in heavy development, things are expected to change **a lot**. 
In one of the recent changes made in the development branch, the way that grasscutter handles web requests has changed. Sadly, this meant that it broke gcgm (even more then it already was) and it is no longer usable until I update the plugin.
I'm kind of limited on time at the moment, but I assure you a fix is coming. However, if you expect to do anything with the plugin atm, you **will** be disappointed.

**Comment by mikuyourworld** [comment]
Thanks for your kind reply.
I will wait.

**Comment by 4Benj** [comment]
> Thanks for your kind reply. I will wait.

The compatibility issue with the latest branch of grasscutter has been fixed in 191704b

**Comment by miaomiao2970** [comment]
.......I think i will never solve the problem.。。。
